#!/bin/bash

# Script to create a PR for updating a cask to a new version
# Usage: ./create-update-pr.sh <cask_name> <new_version>

set -euo pipefail

CASK_NAME="${1:?Cask name required}"
NEW_VERSION="${2:?New version required}"

echo "========================================="
echo "Updating cask: $CASK_NAME"
echo "New version: $NEW_VERSION"
echo "========================================="

# Get current version for reference
CURRENT_VERSION=$(grep -E '^\s*version\s+"[^"]+"' "Casks/${CASK_NAME}.rb" | sed -E 's/.*version\s+"([^"]+)".*/\1/' || echo "unknown")
echo "Current version: $CURRENT_VERSION"

# Check if we're already on this version
if [ "$CURRENT_VERSION" = "$NEW_VERSION" ]; then
  echo "Cask is already at version $NEW_VERSION"
  exit 0
fi

# Create a new branch for the update
BRANCH_NAME="automated-update/${CASK_NAME}-${NEW_VERSION}"
git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"

echo ""
echo "Running brew bump-cask-pr..."
echo "This will download binaries and calculate SHA256 checksums"
echo ""

# Run brew bump-cask-pr
# --no-browse: Don't open browser
# --no-fork: Don't fork the repo (we're already in it)
# --write-only: Only write changes, don't create PR (we'll create it separately for more control)
brew bump-cask-pr \
  --version="$NEW_VERSION" \
  --no-browse \
  --write-only \
  "$CASK_NAME" || {
    echo "ERROR: brew bump-cask-pr failed for $CASK_NAME"
    exit 1
  }

echo ""
echo "Cask file updated successfully"
echo ""

# Check if there are any changes
if git diff --quiet "Casks/${CASK_NAME}.rb"; then
  echo "No changes detected in cask file"
  exit 0
fi

# Show the diff
echo "Changes made:"
git diff "Casks/${CASK_NAME}.rb"
echo ""

# Commit the changes
git add "Casks/${CASK_NAME}.rb"
git commit -m "Update $CASK_NAME to version $NEW_VERSION

Automated update via GitHub Actions.

- Updated version from $CURRENT_VERSION to $NEW_VERSION
- Updated SHA256 checksums

Co-Authored-By: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

echo ""
echo "Changes committed to branch: $BRANCH_NAME"
echo ""

# Push the branch
git push -u origin "$BRANCH_NAME" --force

echo ""
echo "Branch pushed to origin"
echo ""

# Create the PR using gh CLI
PR_TITLE="Update $CASK_NAME to version $NEW_VERSION"
PR_BODY="## Automated Cask Update

**Cask**: \`$CASK_NAME\`
**Previous Version**: \`$CURRENT_VERSION\`
**New Version**: \`$NEW_VERSION\`

### Changes
- ✅ Updated version string
- ✅ Updated SHA256 checksums for all architectures
- ✅ Verified download URLs

### Validation
This PR will be automatically validated with:
- \`brew audit --cask $CASK_NAME\`
- \`brew style --fix $CASK_NAME\`

If validation passes, the PR will be auto-merged.

---
🤖 Generated by [GitHub Actions Auto-Update Workflow](https://github.com/$GITHUB_REPOSITORY/actions)"

# Create PR
gh pr create \
  --title "$PR_TITLE" \
  --body "$PR_BODY" \
  --base main \
  --head "$BRANCH_NAME" \
  --label "automated-update" \
  --label "cask-update" || {
    echo "WARNING: PR creation failed, but changes are committed and pushed"
    echo "You may need to create the PR manually or it may already exist"
    # Don't exit with error - the changes are pushed and that's what matters
  }

echo ""
echo "========================================="
echo "PR created successfully for $CASK_NAME"
echo "========================================="
