#!/bin/bash

# Script to create a PR for updating a cask or formula to a new version
# Usage: ./create-update-pr.sh <name> <new_version> <type>
# type: "cask" or "formula"

set -euo pipefail

NAME="${1:?Name required}"
NEW_VERSION="${2:?New version required}"
TYPE="${3:-cask}"  # Default to cask for backward compatibility

echo "========================================="
echo "Updating $TYPE: $NAME"
echo "New version: $NEW_VERSION"
echo "========================================="

# Determine the directory and file path based on type
if [ "$TYPE" = "formula" ]; then
  FILE_DIR="Formula"
  FILE_PATH="Formula/${NAME}.rb"
  BREW_CMD="bump-formula-pr"
else
  FILE_DIR="Casks"
  FILE_PATH="Casks/${NAME}.rb"
  BREW_CMD="bump-cask-pr"
fi

# Get the tap directory (brew writes changes there, not to checkout dir)
TAP_DIR=$(brew --repository impuls42/tap)
TAP_FILE_PATH="${TAP_DIR}/${FILE_PATH}"

echo "Checkout directory: $(pwd)"
echo "Tap directory: $TAP_DIR"

# Verify the file exists
if [ ! -f "$FILE_PATH" ]; then
  echo "ERROR: File not found: $FILE_PATH"
  exit 1
fi

# Get current version for reference
CURRENT_VERSION=$(grep -E '^\s*version\s+"[^"]+"' "$FILE_PATH" | sed -E 's/.*version\s+"([^"]+)".*/\1/' || echo "unknown")
echo "Current version: $CURRENT_VERSION"

# Check if we're already on this version
if [ "$CURRENT_VERSION" = "$NEW_VERSION" ]; then
  echo "$TYPE is already at version $NEW_VERSION"
  exit 0
fi

# Create a new branch for the update
BRANCH_NAME="automated-update/${NAME}-${NEW_VERSION}"
git checkout -b "$BRANCH_NAME" 2>/dev/null || git checkout "$BRANCH_NAME"

echo ""
echo "Running brew $BREW_CMD..."
echo "This will download binaries and calculate SHA256 checksums"
echo ""

# Run the appropriate brew bump command
# --no-browse: Don't open browser
# --no-fork: Don't fork the repo (we're already in it)
# --write-only: Only write changes, don't create PR (we'll create it separately for more control)
brew "$BREW_CMD" \
  --version="$NEW_VERSION" \
  --no-browse \
  --write-only \
  "$NAME" || {
    echo "ERROR: brew $BREW_CMD failed for $NAME"
    exit 1
  }

echo ""
echo "$TYPE file updated successfully"
echo ""

# Copy the updated file from tap directory back to checkout directory
# (brew bump-*-pr writes to tap dir, not checkout dir)
if [ -f "$TAP_FILE_PATH" ]; then
  cp "$TAP_FILE_PATH" "$FILE_PATH"
  echo "Copied updated file from tap directory"
else
  echo "WARNING: Could not find updated file at $TAP_FILE_PATH"
fi

# Check if there are any changes
if git diff --quiet "$FILE_PATH"; then
  echo "No changes detected in $TYPE file"
  exit 0
fi

# Show the diff
echo "Changes made:"
git diff "$FILE_PATH"
echo ""

# Commit the changes
git add "$FILE_PATH"
git commit -m "Update $NAME to version $NEW_VERSION

Automated update via GitHub Actions.

- Updated version from $CURRENT_VERSION to $NEW_VERSION
- Updated SHA256 checksums

Co-Authored-By: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

echo ""
echo "Changes committed to branch: $BRANCH_NAME"
echo ""

# Push the branch
git push -u origin "$BRANCH_NAME" --force

echo ""
echo "Branch pushed to origin"
echo ""

# Capitalize the type for display
TYPE_DISPLAY=$(echo "$TYPE" | sed 's/^./\U&/')

PR_TITLE="Update $NAME to version $NEW_VERSION"
PR_BODY="## Automated ${TYPE_DISPLAY} Update

**${TYPE_DISPLAY}**: \`$NAME\`
**Previous Version**: \`$CURRENT_VERSION\`
**New Version**: \`$NEW_VERSION\`

### Changes
- Updated version string
- Updated SHA256 checksums for all architectures
- Verified download URLs

---
Generated by [GitHub Actions Auto-Update Workflow](https://github.com/$GITHUB_REPOSITORY/actions)"

# Check if a PR already exists for this branch
EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number' 2>/dev/null || echo "")

if [ -n "$EXISTING_PR" ]; then
  echo "PR #$EXISTING_PR already exists for branch $BRANCH_NAME"
  echo "Updating existing PR..."
  
  # Update the PR title and body
  gh pr edit "$EXISTING_PR" \
    --title "$PR_TITLE" \
    --body "$PR_BODY"
  
  echo ""
  echo "========================================="
  echo "PR #$EXISTING_PR updated successfully for $NAME"
  echo "========================================="
else
  echo "Creating new PR..."
  
  # Create PR with automatic label and request review from repo owner
  gh pr create \
    --title "$PR_TITLE" \
    --body "$PR_BODY" \
    --base main \
    --head "$BRANCH_NAME" \
    --label "automatic" \
    --reviewer "${GITHUB_REPOSITORY_OWNER}"
  
  echo ""
  echo "========================================="
  echo "PR created successfully for $NAME"
  echo "========================================="
fi
